spring:
  application:
    name: product-catalog-api

  datasource:
    url: jdbc:mysql://localhost:3306/catalog
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver # Good practice to be explicit

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration